#!/usr/bin/env bash
# -*- coding: utf8 -*-

# ----------
# SETUP STEPS
# w Deepseek, 62610720, and a few (2?) days prior
# ----------
# sudo vim /etc/nginx/sites-available/webscraper
		# server {
		#     listen 80;
		#     server_name 87.106.66.163; 

		#     location = /favicon.ico { access_log off; log_not_found off; }
		#     location /staticfiles/ {
		#         root /root/webscraper/;
		#     }

		#     location / {
		#         include proxy_params;
		#         proxy_pass http://unix:/root/webscraper/django_app.sock;
		#     }

		#     # location / {
		#     #    proxy_pass http://127.0.0.1:8000;
		#     #    proxy_set_header Host $host;
		#     #    proxy_set_header X-Real-IP $remote_addr;
		#     # }    
		# }

# sudo ln -s /etc/nginx/sites-available/webscraper /etc/nginx/sites-enabled/
# sudo vim /etc/systemd/system/gunicorn.service
# 	(removing to let gunicorn regenerate: sudo mv /etc/systemd/system/gunicorn.service /etc/systemd/system/gunicorn.service.removed)

		# [Unit]
		# Description=gunicorn daemon
		# After=network.target

		# [Service]
		# User=root
		# Group=www-data
		# WorkingDirectory=/root/webscraper
		# ExecStart=/root/webscraper/venv/bin/gunicorn --workers 3 --bind unix:/root/webscraper/django_app.sock django_app.wsgi:application

		# [Install]
		# WantedBy=multi-user.target


# sudo nginx -t
# systemctl restart nginx
# sudo systemctl restart gunicorn
# sudo systemctl enable gunicorn
# systemctl daemon-reload # ulterior gunicorn conf file changes... 
#
# vim /var/log/nginx/error.log 
# ----------

gunicorn django_app.wsgi:application
