# Generated by Django 5.1.5 on 2025-01-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webscrape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "website_url",
                    models.CharField(
                        default="https://wwww.truthfinder.com/", max_length=200
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("middle_name", models.CharField(max_length=200)),
                ("middle_initials", models.CharField(max_length=6)),
                ("age", models.IntegerField(max_length=3)),
                ("city", models.CharField(max_length=200, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CA", "California"),
                            ("FL", "Florida"),
                            ("NJ", "New Jersey"),
                            ("WA", "Washington"),
                            ("WI", "Wisconsin"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("CM", "Cameroon"),
                            ("CA", "Canada"),
                            ("FR", "France"),
                            ("NG", "Nigeria"),
                            ("US", "USA"),
                            ("UK", "United Kingdom"),
                        ],
                        default="US",
                        max_length=2,
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
