# Generated by Django 5.1.5 on 2025-01-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webscraping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webscrape",
            name="task_id",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="webscrape",
            name="task_name",
            field=models.CharField(
                default="truthfinder.sequences/find-person-in-usa-by-firstname-and-lastname.sequence.json",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="webscrape",
            name="task_variables",
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="website_url",
            field=models.CharField(
                default="https://www.truthfinder.com/people-search/", max_length=200
            ),
        ),
    ]
