# Generated by Django 5.1.5 on 2025-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webscraping", "0004_alter_webscrape_task_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webscrape",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
