# Generated by Django 5.1.5 on 2025-01-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webscraping", "0006_alter_webscrape_task_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webscrape",
            old_name="first_name",
            new_name="firstName",
        ),
        migrations.RenameField(
            model_name="webscrape",
            old_name="last_name",
            new_name="lastName",
        ),
        migrations.RemoveField(
            model_name="webscrape",
            name="middle_initials",
        ),
        migrations.RemoveField(
            model_name="webscrape",
            name="middle_name",
        ),
        migrations.AddField(
            model_name="webscrape",
            name="middleInitial",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="webscrape",
            name="middleName",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="age",
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CM", "Cameroon"),
                    ("CA", "Canada"),
                    ("FR", "France"),
                    ("NG", "Nigeria"),
                    ("US", "USA"),
                    ("UK", "United Kingdom"),
                ],
                default="US",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CA", "California"),
                    ("FL", "Florida"),
                    ("NJ", "New Jersey"),
                    ("WA", "Washington"),
                    ("WI", "Wisconsin"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
