# Generated by Django 5.1.5 on 2025-01-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webscraping", "0008_webscrape_task_outputs"),
    ]

    operations = [
        migrations.AddField(
            model_name="webscrape",
            name="task_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STARTED", "Started"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="task_name",
            field=models.CharField(
                choices=[
                    (
                        "truthfinder.sequences/find-person-in-usa.sequence.json",
                        "TRUTHFINDER - USA: Find a person",
                    ),
                    (
                        "afriscience.sequences/auteur-soumettre-un-article.sequence.json",
                        "AFRISCIENCE - AUTEUR: Soumettre un article",
                    ),
                ],
                default="truthfinder.sequences/find-person-in-usa.sequence.json",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="task_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="website_url",
            field=models.CharField(
                choices=[
                    ("https://www.truthfinder.com", "truthfinder.com"),
                    ("https://app.afriscience.org", "afriscience.org"),
                ],
                default="https://www.truthfinder.com/",
                max_length=200,
            ),
        ),
    ]
