# Generated by Django 5.1.5 on 2025-01-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webscraping", "0009_webscrape_task_status_alter_webscrape_age_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webscrape",
            old_name="task_outputs",
            new_name="task_output",
        ),
    ]
