# Generated by Django 5.1.5 on 2025-01-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webscraping", "0010_rename_task_outputs_webscrape_task_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="webscrape",
            name="by_list",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="task_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STARTED", "Started"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
