# Generated by Django 5.1.5 on 2025-02-08 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0012_webscrape_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebscrapeTasksQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Default task queue', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='\n            To:\n            - Add tasks to queue\n            - Check and limit to the number or max concurrent tasks from settings\n            The next task in the line is picked up when the previous is completed.\n        ', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='webscrape',
            name='task_queue',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasksqueue_webscrapes', to='webscraping.webscrapetasksqueue'),
        ),
    ]
