# Generated by Django 5.1.5 on 2025-02-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0014_webscrapedata_alter_webscrape_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscrape',
            name='task_todo',
            field=models.CharField(blank=True, choices=[('webscrape_steps_long_running_method', 'Webscrape detailed process steps long running method...')], help_text='The task to be performed for this web scraping job.', max_length=100, null=True),
        ),
    ]
