# Generated by Django 5.1.5 on 2025-02-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0016_webscrape_task_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscrape',
            name='task_status',
            field=models.CharField(blank=True, choices=[('STARTED', 'Started'), ('RUNNING', 'Running'), ('QUEUED', 'Queued'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20, null=True),
        ),
    ]
