# Generated by Django 5.1.5 on 2025-02-21 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0017_alter_webscrape_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(blank=True, max_length=200, null=True)),
                ('task_run_id', models.CharField(blank=True, max_length=50, null=True)),
                ('task_progress', models.IntegerField(default=0)),
                ('task_status', models.CharField(blank=True, choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('QUEUED', 'Queued'), ('STARTED', 'Started')], max_length=20, null=True)),
                ('task_output', models.TextField(blank=True, null=True)),
                ('task_thread_started_at', models.DateTimeField(blank=True, null=True)),
                ('task_thread_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('task_attempts', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='webscrape',
            name='task_queue',
        ),
        migrations.RemoveField(
            model_name='webscrape',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='webscrape',
            name='id',
        ),
        migrations.RemoveField(
            model_name='webscrape',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='webscrape',
            name='task_attempts',
        ),
        migrations.RemoveField(
            model_name='webscrape',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='webscrape',
            name='task_output',
        ),
        migrations.RemoveField(
            model_name='webscrape',
            name='task_progress',
        ),
        migrations.RemoveField(
            model_name='webscrape',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='webscrape',
            name='title',
        ),
        migrations.AddField(
            model_name='webscrape',
            name='threadtask_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webscraping.threadtask'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WebscrapeTasksQueue',
        ),
    ]
