# Generated by Django 5.1.5 on 2025-02-21 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0018_threadtask_remove_webscrape_task_queue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webscrape',
            name='threadtask_ptr',
        ),
        migrations.AddField(
            model_name='webscrape',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webscrape',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webscrape',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='webscrape',
            name='task_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webscrape',
            name='task_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webscrape',
            name='task_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webscrape',
            name='task_run_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='webscrape',
            name='task_status',
            field=models.CharField(blank=True, choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('QUEUED', 'Queued'), ('STARTED', 'Started')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webscrape',
            name='task_thread_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webscrape',
            name='task_thread_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webscrape',
            name='task_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
