# Generated by Django 5.1.5 on 2025-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0019_remove_webscrape_threadtask_ptr_webscrape_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscrape',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
