# Generated by Django 4.2.11 on 2024-04-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.CharField(choices=[('CM', 'Cameroon'), ('CA', 'Canada'), ('FR', 'France'), ('NG', 'Nigeria'), ('US', 'USA'), ('UK', 'United Kingdom')], max_length=2, null=True),
        ),
    ]
