_O='When Free'
_N='☴'
_M='Stopped'
_L='✗'
_K='Completed'
_J='✓'
_I='On Hold'
_H='|'
_G='In Validation'
_F='⌛'
_E='In Progress'
_D='~'
_C='Todo'
_B='↗'
_A='trainingcoursesession'
from django.db import migrations,models
class Migration(migrations.Migration):dependencies=[('app','0003_trainingcourse_trainingcoursesession')];operations=[migrations.AlterField(model_name=_A,name='course_media_final',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='course_media_raw',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='course_media_validated',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='date_published',field=models.DateTimeField(blank=True,null=True)),migrations.AlterField(model_name=_A,name='implemented_in_app',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='in_sales_funnel',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='preparation',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='ready_for_whats_and_gram',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50))]