# Generated by Django 5.1.5 on 2025-01-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_trainingcourse_trainingcoursesession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="course_media_final",
            field=models.CharField(
                choices=[
                    ("↗", "Todo"),
                    ("~", "In Progress"),
                    ("⌛", "In Validation"),
                    ("|", "On Hold"),
                    ("✓", "Completed"),
                    ("✗", "Stopped"),
                    ("☴", "When Free"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="course_media_raw",
            field=models.CharField(
                choices=[
                    ("↗", "Todo"),
                    ("~", "In Progress"),
                    ("⌛", "In Validation"),
                    ("|", "On Hold"),
                    ("✓", "Completed"),
                    ("✗", "Stopped"),
                    ("☴", "When Free"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="course_media_validated",
            field=models.CharField(
                choices=[
                    ("↗", "Todo"),
                    ("~", "In Progress"),
                    ("⌛", "In Validation"),
                    ("|", "On Hold"),
                    ("✓", "Completed"),
                    ("✗", "Stopped"),
                    ("☴", "When Free"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="date_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="implemented_in_app",
            field=models.CharField(
                choices=[
                    ("↗", "Todo"),
                    ("~", "In Progress"),
                    ("⌛", "In Validation"),
                    ("|", "On Hold"),
                    ("✓", "Completed"),
                    ("✗", "Stopped"),
                    ("☴", "When Free"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="in_sales_funnel",
            field=models.CharField(
                choices=[
                    ("↗", "Todo"),
                    ("~", "In Progress"),
                    ("⌛", "In Validation"),
                    ("|", "On Hold"),
                    ("✓", "Completed"),
                    ("✗", "Stopped"),
                    ("☴", "When Free"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="preparation",
            field=models.CharField(
                choices=[
                    ("↗", "Todo"),
                    ("~", "In Progress"),
                    ("⌛", "In Validation"),
                    ("|", "On Hold"),
                    ("✓", "Completed"),
                    ("✗", "Stopped"),
                    ("☴", "When Free"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="ready_for_whats_and_gram",
            field=models.CharField(
                choices=[
                    ("↗", "Todo"),
                    ("~", "In Progress"),
                    ("⌛", "In Validation"),
                    ("|", "On Hold"),
                    ("✓", "Completed"),
                    ("✗", "Stopped"),
                    ("☴", "When Free"),
                ],
                max_length=50,
            ),
        ),
    ]
