# Generated by Django 5.1.5 on 2025-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_trainingcoursesession_course_media_final_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="trainingcoursesession",
            unique_together={("title", "course")},
        ),
    ]
