# Generated by Django 5.1.5 on 2025-01-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_trainingcoursesession_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcourse",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
