# Generated by Django 5.1.5 on 2025-01-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_trainingcourse_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="course_media_final",
            field=models.CharField(
                choices=[
                    ("↗", "TODO"),
                    ("~", "IN_PROGRESS"),
                    ("⌛", "IN_VALIDATION"),
                    ("|", "ON_HOLD"),
                    ("✓", "COMPLETED"),
                    ("✗", "STOPPED"),
                    ("☴", "WHEN_FREE"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="course_media_raw",
            field=models.CharField(
                choices=[
                    ("↗", "TODO"),
                    ("~", "IN_PROGRESS"),
                    ("⌛", "IN_VALIDATION"),
                    ("|", "ON_HOLD"),
                    ("✓", "COMPLETED"),
                    ("✗", "STOPPED"),
                    ("☴", "WHEN_FREE"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="course_media_validated",
            field=models.CharField(
                choices=[
                    ("↗", "TODO"),
                    ("~", "IN_PROGRESS"),
                    ("⌛", "IN_VALIDATION"),
                    ("|", "ON_HOLD"),
                    ("✓", "COMPLETED"),
                    ("✗", "STOPPED"),
                    ("☴", "WHEN_FREE"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="implemented_in_app",
            field=models.CharField(
                choices=[
                    ("↗", "TODO"),
                    ("~", "IN_PROGRESS"),
                    ("⌛", "IN_VALIDATION"),
                    ("|", "ON_HOLD"),
                    ("✓", "COMPLETED"),
                    ("✗", "STOPPED"),
                    ("☴", "WHEN_FREE"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="in_sales_funnel",
            field=models.CharField(
                choices=[
                    ("↗", "TODO"),
                    ("~", "IN_PROGRESS"),
                    ("⌛", "IN_VALIDATION"),
                    ("|", "ON_HOLD"),
                    ("✓", "COMPLETED"),
                    ("✗", "STOPPED"),
                    ("☴", "WHEN_FREE"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="preparation",
            field=models.CharField(
                choices=[
                    ("↗", "TODO"),
                    ("~", "IN_PROGRESS"),
                    ("⌛", "IN_VALIDATION"),
                    ("|", "ON_HOLD"),
                    ("✓", "COMPLETED"),
                    ("✗", "STOPPED"),
                    ("☴", "WHEN_FREE"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trainingcoursesession",
            name="ready_for_whats_and_gram",
            field=models.CharField(
                choices=[
                    ("↗", "TODO"),
                    ("~", "IN_PROGRESS"),
                    ("⌛", "IN_VALIDATION"),
                    ("|", "ON_HOLD"),
                    ("✓", "COMPLETED"),
                    ("✗", "STOPPED"),
                    ("☴", "WHEN_FREE"),
                ],
                max_length=50,
            ),
        ),
    ]
