_O='WHEN_FREE'
_N='☴'
_M='STOPPED'
_L='✗'
_K='COMPLETED'
_J='✓'
_I='ON_HOLD'
_H='|'
_G='IN_VALIDATION'
_F='⌛'
_E='IN_PROGRESS'
_D='~'
_C='TODO'
_B='↗'
_A='trainingcoursesession'
from django.db import migrations,models
class Migration(migrations.Migration):dependencies=[('app','0006_alter_trainingcourse_slug_and_more')];operations=[migrations.AlterField(model_name=_A,name='course_media_final',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='course_media_raw',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='course_media_validated',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='implemented_in_app',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='in_sales_funnel',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='preparation',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50)),migrations.AlterField(model_name=_A,name='ready_for_whats_and_gram',field=models.CharField(choices=[(_B,_C),(_D,_E),(_F,_G),(_H,_I),(_J,_K),(_L,_M),(_N,_O)],max_length=50))]