# Generated by Django 5.1.5 on 2025-02-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_logentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
