# Generated by Django 5.1.5 on 2025-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='General config data...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='\n            Storing general config data in a flexible JSON format,\n            allowing for easy storage and retrieval of structured or unstructured data.\n            It can be used to save data such as:\n                - Global config data\n                - Application scop config data\n            The JSON format allows for flexible storage and easy retrieval of the data.\n        ', null=True)),
                ('json_data', models.JSONField(blank=True, default=dict, help_text='Flexible JSON field to store general config data.', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
