# Generated by Django 4.2.11 on 2024-07-12 15:00

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('darklight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 0, 56, 512878, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='blog_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Le titre du blog ici...', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 0, 56, 513679, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='editors',
            field=models.ManyToManyField(related_name='blogpost_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='images',
            field=models.ManyToManyField(related_name='blogpost_image', to='darklight.image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 0, 56, 512550, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 0, 56, 511970, tzinfo=datetime.timezone.utc)),
        ),
    ]
