# Generated by Django 5.1.5 on 2025-01-22 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darklight", "0003_blogpost_blog_alter_blog_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 22, 10, 55, 49, 50002, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 22, 10, 55, 49, 58628, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 22, 10, 55, 49, 49639, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="date_uploaded",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 22, 10, 55, 49, 49152, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
