# Generated by Django 5.1.5 on 2025-01-28 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "darklight",
            "0014_alter_blog_date_created_alter_blogpost_date_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 28, 14, 59, 37, 493477, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 28, 14, 59, 37, 502192, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 28, 14, 59, 37, 493129, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="date_uploaded",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 28, 14, 59, 37, 492659, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
