# Generated by Django 4.2.11 on 2024-07-12 15:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('darklight', '0002_alter_blog_date_created_alter_blog_editors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogpost_blog', to='darklight.blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 12, 29, 574288, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 12, 29, 575055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 12, 29, 573970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 12, 29, 573412, tzinfo=datetime.timezone.utc)),
        ),
    ]
