# Generated by Django 5.1.5 on 2025-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webscraping", "0002_webscrape_task_id_webscrape_task_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webscrape",
            name="task_progress",
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="webscrape",
            name="website_url",
            field=models.CharField(
                choices=[("TRUTHFINDER", "www.truthfinder.com")],
                default="https://www.truthfinder.com/",
                max_length=200,
            ),
        ),
    ]
